language: node_js

node_js:
  - '12'

install:
  - yarn --frozen-lockfile

script:
  - yarn run lint
  - yarn run test

after_success:
  - yarn run coveralls

deploy:
  provider: script
  skip_cleanup: true
  script: '//registry.npmjs.org/:_authToken=$NPM_TOKEN > ~/.npmrc && yarn run semantic-release'
