language: node_js

node_js:
  - "6"

env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=lint
  - TEST_TYPE=flow
  - TEST_TYPE=build

install:
  - npm i

script:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run test
    elif [ "$TEST_TYPE" = build ]; then
      npm run build:lib
    elif [ "$TEST_TYPE" = lint ]; then
      npm run lint
    elif [ "$TEST_TYPE" = flow ]; then
      npm run flow
    fi

after_success:
  - |
    if [ "$TEST_TYPE" = test ]; then
      npm run coveralls
    fi

deploy:
  provider: script
  skip_cleanup: true
  script: ./travis-deploy.sh
  on:
    tags: true
